//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Kévin Budain @lowki93
//

import UIKit

class ___FILEBASENAMEASIDENTIFIER___InteractorDatabase: ___FILEBASENAMEASIDENTIFIER___DatabaseInterface {
	weak var presenter: ___FILEBASENAMEASIDENTIFIER___Interface!

	deinit {
        print("::: deinit ___FILEBASENAMEASIDENTIFIER___InteractorDatabase")
    }
}