//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Kévin Budain @lowki93
//

import Foundation

protocol ___FILEBASENAMEASIDENTIFIER___ApiInterface: class {
	weak var presenter: ___FILEBASENAMEASIDENTIFIER___Interface? { get set }
}