//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Kévin Budain @lowki93
//

import UIKit

class ___FILEBASENAMEASIDENTIFIER___Presenter: ___FILEBASENAMEASIDENTIFIER___Interface {

	// MARK: Instances variables
    weak var view: ___FILEBASENAMEASIDENTIFIER___ViewInterface?
    let current___FILEBASENAMEASIDENTIFIER___InteractorDatabase = ___FILEBASENAMEASIDENTIFIER___InteractorDatabase()
    var database: ___FILEBASENAMEASIDENTIFIER___DatabaseInterface?
    let current___FILEBASENAMEASIDENTIFIER___InteractorApi = ___FILEBASENAMEASIDENTIFIER___InteractorApi()
    var api: ___FILEBASENAMEASIDENTIFIER___ApiInterface?

    deinit {
        print("::: deinit ___FILEBASENAMEASIDENTIFIER___Presenter")
    }

    init() {
    	self.current___FILEBASENAMEASIDENTIFIER___InteractorDatabase.presenter = self
    	self.database = self.current___FILEBASENAMEASIDENTIFIER___InteractorDatabase
    	self.current___FILEBASENAMEASIDENTIFIER___InteractorApi.presenter = self
    	self.api = self.current___FILEBASENAMEASIDENTIFIER___InteractorApi
    }

}
